Solution/Python/BinarySearch.py, Solution/Python/LinearSearch.py
Issue #5 
I have added search algorithms in Python in folder Solutions->Python.
Please check, then I can add more
=> Adding search algorithms in python

ADD/algorithms/mergesort.cpp
=> added mergesort algorithm

ADD/Data-Structures/LL.cpp, ADD/Data-Structures/stack.cpp
modified the type error of data structure dir in the ADD
please check this out
=> typo-error

ADD/algorithms/TreeTraversal.cpp
=> added TreeTraversal Algo

ADD/algorithms/binary_search.cpp
=> added binary search algorithm inside ADD/algorithm folder

ADD/algorithms/selectionSort.c
This is Selection Sort Using C programming.
=> Selection Sort Using C Programming

Competitive_Programming_Question_and_Solution/1011.Capacity_To_Ship.py, Competitive_Programming_Question_and_Solution/162.find_peak_element.py, Competitive_Programming_Question_and_Solution/50.pow(x,n).py, Competitive_Programming_Question_and_Solution/72.search_2d_matrix.py
Added Leetcode questions and answers for Binary Search - Medium Level
=> Added Leetcode Question and Answers

ADD/algorithms/IncreasingArray.java
=> added Increasing Array

ADD/Data-Structures/Stack.py
Stack Using Python Programming without Queue Module.
=> Stack Using Python

Detection of Linked list.cpp
=> linked list problem

ADD Display Armstrong Number Between Intervals
IT IS A CPP CODE WHCIH CAN DISPLAY ARMSTRONG NUMBER BETWEEN TWO NUMBER OR IN AN INTERVAL
kindly accept my pull request and add hacktoberfest2020 accepted.
thank you !!!
hacktoberfest2020 ROCK!!!!!!!!!!!!!
=> Display Armstrong Number Between Intervals

transposeofamatrix.cpp
This is a detailed program illustrating the transpose of a matrix i.e a program which interchanges the rows and columns of a matrix.
=> Transpose of a matrix

ADD/algorithms/RecursiveInsertionSort.java
=> Add Recursive Insertion Sort to Algorithm #5

Solution/Python/Kadane_Algorithm.py
Simple code in python explaining Kaden's algorithm.
Fixes #5
=> Kaden's Algorithm

parenthesis matching.cpp
This is a program for parenthesis matching. Parenthesis matching is basically an application of STACK. This question is asked in many of the competitive programming contests.
=> Parenthesis matching STACK

ADD/Data-Structures/StackConsoleApp.py
Let me know if there are any changes needed and I will also do LL in Python are you open to more modern languages as well (Kotlin/C#/JS/Etc)?
=> + Added a Stack Console App for Data-Structures (Python)

Solution/Kotlin/bubblesort.kt
+ Basic Kotlin Bubble sort you can run it in the emulator here: https://play.kotlinlang.org/
=> Added simple bubble sort for kotlin

Solution/JS/bubblesort.js
Added a file to solution JS for BubbleSort
=> Added Bubble Sort JS Algorithm

impliment_linklist.c
implemented link list in c, we can insert and delete anywhere from the link list.
=> Implemented Linklist

gameonpython
user have to guess randomly generated words
=> game on python

Reverse a linked list.
=> Create Reverse a linked list.

bst.cpp
bst using linked list implementation
=> binary search tree

MinSpanTree.cpp, bst.cpp
C++ program to find mst from a given graph
=> minimum spanning tree

duplicatecharacters
program to find duplicate characters in a string
=> duplicate charaters

ADD/algorithms/Kandanes Algorithm.cpp
Kadane’s algorithm is used to find out the maximum subarray sum from an array of integers. Elements can be either positive or negative.
=> Create Kandanes Algorithm.cpp

Solution/C++/Kadane's Algorithm.cpp
Kadane’s algorithm is used to find out the maximum subarray sum from an array of integers. The time complexity of the algorithm is O(n) and Space Complexity is O(1)
=> Kadane's Algorithm
